language: go

go:
  - master # This uses automatically the latest version of go

install:
  - go get github.com/spf13/hugo # This provides the latest version of Hugo to Travis CI

script:
  - hugo # This commands builds your website on travis

deploy:
  local_dir: public # Default static site output dir for Hugo
  repo: paris-ci/Arthur_Knowledgebase # This is the slug of the repo you want to deploy your site to
  target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GUTHUB_TOKEN # Yeah that was a fail on config but shrug, as long as it works
  committer-from-gh: true
  verbose: true
  keep-history: true
  on:
    branch: master
